### ISSUE TITLE
Get feedback from manga-py

### ISSUE THREAD

**Issue by gromenauer** [gromenauer/manga_py_update#1]
Hi @1271,

I use this script to automate manga-py usage. Try it and see if you like it.
It's useful to me as is, but I don't know if it fits wit your manga-py vision. Is redundant with manga-py 2? Do you want to incoroprate it to manga py as pull request? or better as is?

In the future I want to add a yaml config to:
* Specify dirs to update
* Rename comics (and get old names, to search for duplicates)
* Change url comic sources (idem, historic for duplicates)
...

This repository was asked for in https://github.com/yuru-yuri/manga-py/issues/150
This kind of repo should be in https://github.com/manga-py organization?

**Comment by 1271** [comment]
For manga-py 2 this will be redundant, but I will be glad if you develop this
> This kind of repo should be in https://github.com/manga-py organization?

If you think this is not necessary, I am for

**Comment by gromenauer** [comment]
> For manga-py 2 this will be redundant, but I will be glad if you develop this

OK. I will use it until manga-py 2 is out.
And will update with whatever I use in it. 

> If you think this is not necessary, I am for

I don't understand this fully. Anyway, I have no problem with any option 
If you want something just let me know :smile:

**Comment by 1271** [comment]
> I don't understand this fully.

I will not be against :-)
Excuse me. Some speech turns are difficult for me to translate yet.

**Comment by gromenauer** [comment]
I hope not to put Spanish turns in English for you to traduce to Russian X)
